### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by odiseo0** [supabase-community/realtime-py#41]
This issue should have been a discussion but since discussions aren't open I guess it's fine if we discuss it here.

Is there a goal or roadmap for a next release, something planned?

**Comment by anand2312** [comment]
Apologies for the delay.

Firstly, good point about discussions - I'll try getting that set up now.

Right now there's no clear roadmap for a new release, because although the supabase python libraries are community libraries it's mainly the 4 of us maintainers who're working on them, and this repo has been sort of on the backburner while we worked on the other libraries (postgrest-py, storage-py, gotrue-py etc). We'd be happy to review and merge contributions here too though!

A sort of rough roadmap I've had for some time:
- Remove the synchronous interfaces this library provides
- Try and complete these three issues: 
    [ ] supabase-community/supabase-py#73
    [ ] supabase-community/supabase-py#89
    [ ] supabase-community/supabase-py#107 
    
I'm happy to hear more suggestions!

**Comment by odiseo0** [comment]
Thanks for the response, I'll check for the issues and will try to contribute to a solution for them.

I was asking because our team needs to use a higher version of `websockets` with was merge but isn't on the package for pypi yet.

**Comment by odiseo0** [comment]
Sorry for late response, I'm sick.
Currently realtime is using `websockets` 10.3 but the released version is using 9.2 I think.
